# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393



rcpp_saem_interface <- function(model_sexp, data_sexp, weight_flag, debug_flag, optimization_flag, hessian_flag, verbose) {
    .Call(`wrap_rcpp_saem_interface`, model_sexp, data_sexp, weight_flag, debug_flag, optimization_flag, hessian_flag, verbose)
}