# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dynr_hello_world <- function() {
    print('.call')
    .Call(`rcpparma_hello_world`)
	print('func')
	rcpparma_hello_world()
}

hello_world <- function() {
    .Call(`rcpparma_hello_world`)
}
